### ISSUE TITLE
DnsServerSetting: PowerShell Cmdlet failed: Convert property `'AllowUpdate'` value from type `'BOOLEAN'` to type `'UINT32'` failed

### ISSUE THREAD

**Issue by blackdynamite595** [dsccommunity/DnsServerDsc#101]
#### Details of the scenario you tried and the problem that is occurring

Trying to set DNS setting "AllowUpdate" to true.

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, true
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```
or

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, '1'
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```

#### Verbose logs showing the problem
    ================================================================================
    Error executing action `run` on resource 'dsc_resource[authoritative_settings]'
    ================================================================================

    Chef::Exceptions::PowershellCmdletException
    -------------------------------------------
    PowerShell Cmdlet failed: Convert property 'AllowUpdate' value from type 'BOOLEAN' to type 'UINT32' failed
     At line:12, char:2
     Buffer:
    horitative_settings";
    };^
    insta
        + CategoryInfo          : SyntaxError: (root/Microsoft/...gurationManager:String) [], CimException
        + FullyQualifiedErrorId : MiClientApiError_Failed
        + PSComputerName        : localhost

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/fisher-dns-windows/recipes/default.rb

     70:        dsc_resource 'authoritative_settings' do
     71:                module_name 'xDnsServer'
     72:                resource :xDnsServerSetting
     73:                property :Name, 'authoritative_settings'
     74:                property :NoRecursion, true
     75:                property :LogLevel, 24865
     76:                property :AllowUpdate, true
     77:                property :LogFilePath, 'C:\\dns\\dns.log'
     78:                #property :ListenAddresses, dnsip
     79:                ignore_failure true
     80:        end
     81:        registry_key "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\DNS\\Parameters" do

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/fisher-dns-windows/recipes/default.rb:70:in `from_file'

    dsc_resource("authoritative_settings") do
      action [:run]
      default_guard_interpreter :default
      properties {Name=>"authoritative_settings", NoRecursion=>true, LogLevel=>24865, AllowUpdate=>true, LogFilePath=>"C:\\dns\\dns.log"}
      resource :xDnsServerSetting
      declared_type :dsc_resource
      cookbook_name "fisher-dns-windows"
      recipe_name "default"
      module_name "xDnsServer"
      ignore_failure true
    end

    System Info:
    ------------
    chef_version=14.10.9
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, true
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```
or

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, '1'
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19376.amd64fre.winblue_ltsb_escrow.190520-1700
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.13.0.0

**Comment by omiossec** [comment]
Hello, 

I am testing the same setup in PowerShell, with the version 1.15.0.0

```powershell 
configuration DnsSet {
    param
    (
        # Target nodes to apply the configuration
        [string[]]$NodeName = 'localhost'
    )
Import-DscResource -Module xDnsServer, PSDesiredStateConfiguration

Node $NodeName
    {
        xDnsServerSetting SetupDns
        {
            Name = "authoritative_settings"
            NoRecursion = $true
            LogLevel = 24865
            AllowUpdate = $true
            LogFilePath = "C:\dns\dns.log"
        }
    }
}
```
It work as expected

**Comment by johlju** [comment]
The property `AllowUpdate` should be set to a numeric value and not a boolean value. See the property `AllowUpdate` here https://docs.microsoft.com/en-us/windows/win32/dns/microsoftdns-server .

We should add a link to this reference so it easier to find the available values.

**Comment by johlju** [comment]
In PR #185 the resource is getting refactored to use cmdlet `Set-DnsServerSetting` then AllowUpdate is changed to `Boolean` as that is what the cmdlet expects.
