### ISSUE TITLE
DnsServerDsc: Consider renaming the module

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DnsServerDsc#179]
Suggest we consider renaming the module from xDnsServer to DnsServerDsc since 'x' no longer have any meaning. This is inline with the other modules that have been renamed. This should also remove the 'x' from all the resource names.

**Comment by johlju** [comment]
At the same time we should change the resource prefixes from MSFT to DSC to indicate that it is the DSC Community that maintains the resources.

**Comment by gaelcolas** [comment]
I think it'd be great to do that when the current PRs are merged and released to PSGallery.
We could release 2.0.0 (after all pre-releases are out), and then upgrade the repo (rename, and make the code change, and the Pipeline change).
Then we could release DnsServerDsc as v2.1.0 and unlist the old xDnsServer from the gallery (invisible but still accessible if you install specific/pinned version.

I'd be happy to give a hand, @Sudman1, @indented-automation, @johlju we'd just need to sync our efforts.

**Comment by johlju** [comment]
DnsServerDsc will be release as 3.0.0 as it will be breaking change with new module name and also there will be breaking changes that we don't add to the 2.0.0 release.
