### ISSUE TITLE
Resources DnsServerA, DnsServerPtr, and DnsServerCName missing in DnsServerDsc 3.0.0

### ISSUE THREAD

**Issue by Yvand** [dsccommunity/DnsServerDsc#264]
### Details of the scenario you tried and the problem that is occurring

I cannot find resources DnsServerA, DnsServerPtr, and DnsServerCName in DnsServerDsc 3.0.0.
I'm not sure if I missed something obvious, but I simply cannot find them, either in the file system or with powershell:

```powershell
Install-Module -Name DnsServerDsc
Get-DscResource -Module DnsServerDsc | fl Name
```

### Verbose logs showing the problem

```
Get-DscResource -Module DnsServerDsc | select Name

Name
----
DnsServerADZone
DnsServerClientSubnet
DnsServerConditionalForwarder
DnsServerDiagnostics
DnsServerForwarder
DnsServerPrimaryZone
DnsServerRootHint
DnsServerSecondaryZone
DnsServerSetting
DnsServerSettingLegacy
DnsServerZoneAging
DnsServerZoneScope
DnsServerZoneTransfer
```

### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

### The operating system the target node is running

```
OsName               : Microsoft Windows 10 Entreprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, fr-FR}
```

### Version and build of PowerShell the target node is running

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version of the DSC module that was used

```
Name         Version Path
----         ------- ----
DnsServerDsc 3.0.0   C:\Users\yvand\Documents\PowerShell\Modules\DnsServerDsc\3.0.0\DnsServerDsc.psd1
```

**Comment by johlju** [comment]
You must use Windows PowerShell (5.1) to see those DSC resources. A future version of PowerShell will be able to show them.

**Comment by johlju** [comment]
Or rather DSC will be moved out of PowerShell and into a separate module which will be installed independent of PowerShell.

**Comment by Yvand** [comment]
Indeed, if I install DnsServerDsc in "Windows PowerShell", the DSC resources apperar.
But this requirement makes this module impossible to use it for me, because most of the DSC modules are installed in PowerShell 7.1, and won't be visible in an editor which uses "Windows PowerShell" 5.1.
I will stick to xDnsServer for the time being.

**Comment by johlju** [comment]
Keep an eye out for DSCv3 which will probably resolve this (but I can’t be 100%). 

Since we can’t resolve this in this repo (without moving backwards to MOF-based) I will go ahead and close this issue. Thanks for reporting it!
