### ISSUE TITLE
Stream redirection in tests, either comment or code is incorrect.

### ISSUE THREAD

**Issue by csandfeld** [dsccommunity/DnsServerDsc#274]
Throughout 65 `.tests.ps1` files in this project, there are lines such as these:

https://github.com/dsccommunity/DnsServerDsc/blob/bec927aec4e07243b52d76736bd1a989c018618f/tests/Unit/DSC_DnsServerADZone.Tests.ps1#L20-L21

Either the comment is wrong, or the code is wrong since in the code the `Error` stream IS being redirected to null, while the `Warning` stream is not.

I will be happy to submit a PR fixing either the comment or the code, if someone can tell me what the actual intention is.

**Comment by johlju** [comment]
The intention was that only error messages should surface to the console to minimize (remove) output when running the tests. So if any error occurred when running task `noop` it should show, but no other output. 🙂

**Comment by csandfeld** [comment]
Ok - I'll submit a PR to get that fixed then 🙂
